version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java_app
    ports:
      - "9003:9003"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:n123n@mongodb:27017/customers?authSource=admin
    networks:
      - app_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: n123n
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: