server:
  port: 9003

spring:
  application:
    name: bpicustomer
  data:
    mongodb:
      database: "BpiDB"
      uri: mongodb://root:n123n@mongodb:27017/customers?authSource=admin
  logging:
    path: ./logs
    max:
      size: 10 MB